spring:
  application:
    name: catalog
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9001
#spring:
#  application:
#    name: catalog
#  profiles:
#    active: dev
#  config:
#    import: "optional:configserver:http://localhost:9101/catalog/dev"
#  cloud:
#    config:
#      uri: http://localhost:9101
#      username: devstore
#      password: secr3t
