version: 2
updates:
  - directory: /service/rating
    package-ecosystem: gradle
    target-branch: develop    
    schedule:
      interval: weekly
  - directory: /service/catalog
    package-ecosystem: gradle
    target-branch: develop    
    schedule:
      interval: weekly