version: 2
updates:
  - directory: ./
    package-ecosystem: gradle
    target-branch: develop    
    schedule:
      interval: weekly
  - directory: /rating-service
    package-ecosystem: gradle
    target-branch: develop    
    schedule:
      interval: weekly
  - directory: /catalog-service
    package-ecosystem: gradle
    target-branch: develop    
    schedule:
      interval: weekly