- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name: 
          - wget
          - tar
        state: present

    - name: Download and extract Flyway
      shell: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/{{ flyway_version }}/flyway-commandline-{{ flyway_version }}-linux-x64.tar.gz | tar -xz -C /opt

    - name: Create a symbolic link for Flyway
      file:
        src: /opt/flyway-{{ flyway_version }}/flyway
        dest: /usr/local/bin/flyway
        state: link
        force: yes

    - name: Verify Flyway installation
      shell: flyway -v
      register: flyway_version_output
      ignore_errors: yes

    - name: Display Flyway version
      debug:
        msg: "{{ flyway_version_output.stdout }}"