global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "node"
    static_configs:
      - targets: ["config-server:8888","discovery-server:8761","api-gateway:8080"]