global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: spring-boot-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - tracing-server:9411 
        - config-server:8888
        - discovery-server:8761
        - api-gateway:8080
        # - catalog-server:9001
        # - rating-service:9002