version: "3"

x-project:
  name: devstore

services:

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}    
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    network_mode: host
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 3s
      timeout: 1s
      retries: 10

  tracing:
    image: openzipkin/zipkin
    container_name: tracing
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    network_mode: host

  config:
    image: crosstraining/config-server:0.0.33  
    container_name: config
    restart: always
    environment:
      - PORT=8888
      - CONFIG_SERVICE_REPO_URI=https://github.com/cross-training/devstore-config.git
      - CONFIG_SERVICE_REPO_LABEL=main
      - CONFIG_SERVICE_REPO_PATHS=services
      - CONFIG_SERVICE_REPO_USERNAME=''
      - CONFIG_SERVICE_REPO_PASSWORD=''
      - CONFIG_SERVICE_USERNAME=devstore
      - CONFIG_SERVICE_PASSWORD=secr3t
      - TRACE_SERVICE_URI=http://localhost:9411      
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - tracing
    network_mode: host
  
  discovery:
    image: crosstraining/discovery-service:0.0.33
    container_name: discovery
    environment:
      - PORT=8761
      - CONFIG_SERVICE_URI=http://localhost:8888
      - CONFIG_SERVICE_USERNAME=devstore 
      - CONFIG_SERVICE_PASSWORD=secr3t
      - TRACE_SERVICE_URI=http://localhost:9411   
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config:
        condition: service_healthy
    network_mode: host

  gateway:
    image: crosstraining/api-gateway:0.0.33
    container_name: gateway
    environment:
      - PORT=8080
      - CONFIG_SERVICE_URI=http://localhost:8888
      - CONFIG_SERVICE_USERNAME=devstore
      - CONFIG_SERVICE_PASSWORD=secr3t
      - DISCOVERY_SERVICE_URI=http://localhost:8761/eureka/
      - TRACE_SERVICE_URI=http://localhost:9411       
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3ss
      retries: 10
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy 
    network_mode: host

  catalog:    
    image: crosstraining/devstore-catalog:1.1.39
    container_name: catalog
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      - PORT=9001
      - CONFIG_SERVICE_URI=http://localhost:8888
      - CONFIG_SERVICE_USERNAME=devstore
      - CONFIG_SERVICE_PASSWORD=secr3t
      - DISCOVERY_SERVICE_URI=http://localhost:8761/eureka/
      - TRACE_SERVICE_URI=http://localhost:9411 
      - DB_URL=jdbc:postgresql://localhost:5432/devstore
      - DB_USER=catalog
      - DB_PASSWORD=catalog
      - DB_SCHEMA=catalog  
    healthcheck:
      test: curl --fail http://localhost:9001/actuator/health || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    network_mode: host  

  rating:
    image: crosstraining/devstore-rating:1.1.39
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy 
    environment:
      - PORT=9002
      - CONFIG_SERVICE_URI=http://localhost:8888
      - CONFIG_SERVICE_USERNAME=devstore
      - CONFIG_SERVICE_PASSWORD=secr3t
      - DISCOVERY_SERVICE_URI=http://localhost:8761/eureka/
      - TRACE_SERVICE_URI=http://localhost:9411 
      - DB_URL=jdbc:postgresql://localhost:5432/devstore
      - DB_USER=rating
      - DB_PASSWORD=rating
      - DB_SCHEMA=rating
    healthcheck:
      test: curl --fail http://localhost:9002/actuator/health || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    network_mode: host  
  
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus      
    network_mode: host

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:7.1.5
    container_name: grafana    
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    network_mode: host
    volumes:      
      - ./grafana/provisioning:/etc/grafana/provisioning  