spring:
  application:
    name: devstore
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_PLATFORM}
  h2:
    console:
      enabled: true
server:
  port: ${API_PORT}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always