spring:
  application:
    name: devstore
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_PLATFORM}
server:
  port: 8080