server:
  port: 9101
  bootstrap: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cross-training/devstore-config.git
          search-paths: services
          default-label: main
  security:
    user:
      name: devstore
      password: secr3t
         
