server:
  port: 9101
  bootstrap: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cross-training/devstore.git
          search-paths: config-data
          default-label: develop
  security:
    user:
      name: devstore
      password: pa$$w0rd
         
